# Generated by Django 5.1.1 on 2025-11-24 22:16

import django.db.models.deletion
import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='img',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='photo_prev',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='slug',
            field=models.SlugField(blank=True, default='my-slug', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='source',
            field=models.CharField(default='wikitravel', max_length=50),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='text_html',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='text',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='text_html', verbose_name='Текст новости'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(default='Культура', max_length=50, verbose_name='Тематика')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
                'ordering': ['theme'],
                'indexes': [models.Index(fields=['theme'], name='news_theme_theme_e2fcef_idx')],
            },
        ),
        migrations.AddField(
            model_name='newsstory',
            name='theme',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='news.theme', verbose_name='Тематика'),
        ),
    ]
